language: php

php:
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
